### ISSUE TITLE
How to use ImageNet in FLAVA?

### ISSUE THREAD

**Issue by Phoebe-ovo** [facebookresearch/multimodal#120]
### 🚀 The feature, motivation and pitch

The link of ImageNet datasets https://huggingface.co/datasets/aps/imagenet2012#dataset-summary is not found.

And even if download the imagenet_object_localization_patched2019.tar.gz on kaggle, and set the IMAGENET_TAR, it still download from huggingface. 

But huggingface.co need registration, so the download is always failed, the failing log is :
ConnectionError: Couldn't reach https://huggingface.co/datasets/imagenet-1k/resolve/1500f8c59b214ce459c0a593fa1c87993aeb7700/data/train_
images_0.tar.gz (error 401)

I want to know how to use the dataset?

**Comment by RdoubleA** [comment]
Thanks for bringing this to our attention. This is something we're currently looking into, and we'll update here when it's resolved.

**Comment by RdoubleA** [comment]
This should now be addressed in the [README](https://github.com/facebookresearch/multimodal/blob/main/examples/flava/README.md). Basically, you need a huggingface account with an access token in order to use the dataset.
