### ISSUE TITLE
Deprecate PretrainedMixin

### ISSUE THREAD

**Issue by YosuaMichael** [facebookresearch/multimodal#153]
Following up on [this comment](https://github.com/facebookresearch/multimodal/pull/130#discussion_r919572935).

Currently we use `PretrainedMixin` to enable to load model from url. However this way has restriction that it can only be used for model that have class in TorchMultiModel repository (hence we can add the Mixin). However for use case where the model is from other repository, we can't rely on `PretrainedMixin` (example where we use model from torchvision, or we construct simple model by `nn.Sequential(...)` ) 

Hence I think it is better to use a util function [load_module_from_url](https://github.com/facebookresearch/multimodal/blob/bdbb487bb3e32286453d7791dd7edbdfbd2ce0da/torchmultimodal/utils/common.py#L136) since it offer more flexibility.

This issue is for a plan to deprecate `PretrainedMixin` and use `load_module_from_url` utils function instead.

**Comment by langong347** [comment]
cc @sophiazhi
