### ISSUE TITLE
Fine-tuning flava model

### ISSUE THREAD

**Issue by ans92** [facebookresearch/multimodal#159]
Hi,
Thank you for great model. I want to ask in order to fine-tune the model do I need to crate the account of huggingface or not? I want to fine tune the flava model on my dataset for some downstream task like image classification. So can you please guide me about the steps of fine-tuning of flava model. Thank you.

**Comment by ankitade** [comment]
Hi, it depends on the dataset you want to finetune on. the hugging face account is more for pretraining which requires access to imagenet.

**Comment by ans92** [comment]
Thank you for your reply. I want to finetune the data on MIT-States and C-GQA dataset. So I assume I wouldn't need haggingface account. So in order to fine-tune flava model do I only need to run the following line:
```
python finetune.py config=configs/finetuning/qnli.yaml model.pretrained_model_key=flava_full
```

**Comment by ankitade** [comment]
yes you can try that command to see the qnli results. you will need to integrate your dataset with finetuning code (except  for glue ones where u ca just switch out qnli for another dataset  key)
