### ISSUE TITLE
README links are broken

### ISSUE THREAD

**Issue by mrahtz** [facebookresearch/multimodal#165]
The links to cnn_lstm.py and lstm_encoder.py in the README are broken. They currently point to https://github.com/facebookresearch/multimodal/blob/main/torchmultimodal/models/cnn_lstm.py
and
https://github.com/facebookresearch/multimodal/blob/main/torchmultimodal/modules/encoders/lstm_encoder.py
but I guess they're meant to point to
https://github.com/facebookresearch/multimodal/blob/main/examples/cnn_lstm/cnn_lstm.py
and
https://github.com/facebookresearch/multimodal/blob/main/examples/cnn_lstm/lstm_encoder.py
?

Thanks!

**Comment by RdoubleA** [comment]
You’re right, thanks for pointing this out. They should point to the examples folder. Feel free to submit a pull request, or I can take care of it soon.
