### ISSUE TITLE
'FlavaModelOutput' object has no attribute 'contrastive_logits_per_image'

### ISSUE THREAD

**Issue by ans92** [facebookresearch/multimodal#183]
Hi,
I have tried to run the following code:
```
from PIL import Image
import requests
from transformers import FlavaProcessor, FlavaModel

model = FlavaModel.from_pretrained("facebook/flava-full")
processor = FlavaProcessor.from_pretrained("facebook/flava-full")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = processor(text=["a photo of a cat"], images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)
logits_per_image = outputs.contrastive_logits_per_image  # this is the image-text similarity score
probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities
```
But I am getting an error that 
```
'FlavaModelOutput' object has no attribute 'contrastive_logits_per_image'
```
Can you please help me in this regard. Thank you.

**Comment by RdoubleA** [comment]
This seems to be from the huggingface FlavaModel example. I see you've already posted the same question there. I would defer to whatever advice they have.

Just from looking at the example code and their repo, my guess is you need to replace `FlavaModel` with `FlavaForPretraining` (see [code](https://github.com/huggingface/transformers/blob/3f936df66287f557c6528912a9a68d7850913b9b/src/transformers/models/flava/modeling_flava.py#L1735)). This should return `FlavaForPretrainingOutput` which contains the `contrastive_logits_per_image` field.
