### ISSUE TITLE
Potential bug in CLIP transform implementation

### ISSUE THREAD

**Issue by parmeet** [facebookresearch/multimodal#32]
https://github.com/facebookresearch/multimodal/blob/28d222ad044495e3fe960417e876545123c2aba5/torchmultimodal/transforms/clip_transform.py#L98-L108

In above implementation, ideally the truncation should happen before adding the start/end tokens. If the sentence is long enough, it would remove the end token. 

correct implementation

```python 
 self.text_transform = transforms.Compose( 
     [ 
         tokenizer, 
         text_transforms.Truncate(self.text_max_length-2), 
         text_transforms.AddToken(self.text_start_token, begin=True), 
         text_transforms.AddToken(self.text_end_token, begin=False), 
         StrToIntTransform(), 
         text_transforms.ToTensor(padding_value=0), 
         PadTransform(max_length=self.text_max_length), 
     ] 
 ) 
```

cc: @ebsmothers

**Comment by ebsmothers** [comment]
Hey @parmeet thanks for pointing this out! For our CLIP transform we are using the [open_clip](https://github.com/mlfoundations/open_clip) implementation as our source of truth. There they also apply truncation after adding the start and end tokens ([ref](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/tokenizer.py#L177)).

**Comment by parmeet** [comment]
I see, thanks for the reference. I certainly do not have internal working knowledge for the model, but if removing end of token bring any performance regression for longer sentence, its worth to get it clarified with the authors.
