### ISSUE TITLE
Albef model dataset & caption file

### ISSUE THREAD

**Issue by techthiyanes** [facebookresearch/multimodal#376]
where would we get the dataset file and caption files?
we didn't able to locate albef's text encoder inside the models.

**Comment by ebsmothers** [comment]
Hi @techthiyanes thanks for creating the issue. I just opened #377 which should hopefully address both of these points. If anything is still unclear please let me know!

**Comment by techthiyanes** [comment]
> Hi @techthiyanes thanks for creating the issue. I just opened #377 which should hopefully address both of these points. If anything is still unclear please let me know!

Thanks for providing good ReadMe file. Meanwhile I have been getting the below error on torch dimensions.
RuntimeError: The size of tensor a (19) must match the size of tensor b (13) at non-singleton dimension 1
 Specifically at text collate function.Though i changed the dimension to fix, couldn't succeed. Would you please help me?

**Comment by ebsmothers** [comment]
@techthiyanes mind opening a separate issue for this? Also if you can provide a full traceback together with the command you ran and your environment that would be helpful.
