### ISSUE TITLE
Linear probing on vision tasks

### ISSUE THREAD

**Issue by KMnP** [facebookresearch/multimodal#378]
Hi, Thank you for sharing the code! Can I ask a question regarding the ImageNet linear probing experiments?

In Appendix B.2,  the paper mentions that "We extract image features from the final layer of the image encoder (before the multi-modal encoder) and train a logistic regression classifier (L-BFGS implementation from [80]) on the extracted image features."

I wonder if the image features are the `encoded_image` or the `projected_embeddings`, from the output of the [`encode_image()`](https://github.com/facebookresearch/multimodal/blob/main/torchmultimodal/models/flava/model.py#L225).

Thank you!

**Comment by ankitade** [comment]
Hi, for image net linear probing the encoded_image is used (not projected output) 
https://github.com/facebookresearch/multimodal/blob/main/examples/flava/callbacks/multimodal_eval.py#L66

**Comment by KMnP** [comment]
Thanks for the quick response! 

I wonder if you use any specific augmentations for the linear probing. Maybe I missed something, I couldn't  find the details in the paper.

**Comment by KMnP** [comment]
Hi @ankitade, I wonder for the output dict of `encoded_image`, do you use `pooler_output` or the cls_token embedding from `last_hidden_state`. 

Thank you!

**Comment by ankitade** [comment]
Hi @KMnP, it is the cls token embedding

**Comment by ankitade** [comment]
Hope this answered your questions. Please open another issue if you have more questions
