### ISSUE TITLE
Fine-tuning and scaling up blog post? 

### ISSUE THREAD

**Issue by sayakpaul** [facebookresearch/multimodal#381]
The announcement blog post mentions there will be two more things:

> Apart from the code, we are also releasing a tutorial for fine-tuning multimodal foundation models, and a blog post (with code pointers) on how to scale up such models using techniques from PyTorch Distributed (FSDP and activation checkpointing). We hope such examples and tutorials will serve to demystify a number of advanced features available in the PyTorch ecosystem.

If they are out, could you please help with the links?

**Comment by ankitade** [comment]
Thanks for your interest. Here is the link https://pytorch.org/blog/scaling-multimodal-foundation-models-in-torchmultimodal-with-pytorch-distributed/

**Comment by sayakpaul** [comment]
Might be good to link this in the README. 

@NielsRogge FYI.
