### ISSUE TITLE
Tutorial/reference to finetune FLAVA on custom dataset

### ISSUE THREAD

**Issue by rishabhm12** [facebookresearch/multimodal#392]
### 🚀 The feature, motivation and pitch

Hey guys,
I wanted to finetune FLAVA on custom dataset (image + text + image-text pairs). Could you please provide any reference/steps for doing so? Also, it would be really helpful if you could provide examples on finetuning flava in it's entirety i.e finetuning on MLM + MIM + MMM + ITM + Contrastive Learning.

Thank you!

**Comment by ebsmothers** [comment]
Hi @rishabhm12 thanks for using TorchMultimodal. For FLAVA finetuning you can take a look at the example script [here](https://github.com/facebookresearch/multimodal/blob/main/examples/flava/finetune.py) (also see the [README](https://github.com/facebookresearch/multimodal/blob/main/examples/flava/README.md#finetuning) for the command to launch the script). If you are interested in hooking up a custom dataset, you can check out the [datamodules](https://github.com/facebookresearch/multimodal/blob/main/examples/flava/data/datamodules.py) for an example of how to set things up.
