### ISSUE TITLE
[FLAVA]Can't Access ImageNet

### ISSUE THREAD

**Issue by anyduoshuo** [facebookresearch/multimodal#394]
### 🚀 The feature, motivation and pitch

I already have a huggingface account with an access token，but when I follow the readme to lanuch pretraining by running"python -m flava.train config=flava/configs/pretraining/debug.yaml" firstly, get the failing log :
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.0.0/datasets/imagenet-1k/imagenet-1k.py (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=100)")))

I thought it was a connection issue, but when I type that url “https://raw.githubusercontent.com/huggingface/datasets/2.0.0/datasets/imagenet-1k/imagenet-1k.py” directly into chorme, I get “404 not found”

I want to know how to access the dataset? Thanks a lot!

**Comment by ebsmothers** [comment]
Hi @anyduoshuo have you accepted the terms and conditions on the Hugging Face dataset page [here](https://huggingface.co/datasets/imagenet-1k)? I would also suggest fully following the instructions in the README [here](https://github.com/facebookresearch/multimodal/blob/403b53ab14e1cdaa1d3e8c00f0abcff87f53bc10/examples/flava/README.md#access-imagenet) just to make sure there are no differences in your setup.

**Comment by ankitade** [comment]
I was able to download the dataset using the readme so it is likely a connection or permission issue. can you reopen the issue or create new one if you still need help from us
