### ISSUE TITLE
training flava with ddp and activation checkpointing gives runtime error

### ISSUE THREAD

**Issue by rxqy** [facebookresearch/multimodal#404]
Hi, I'm following the [tutorial](https://pytorch.org/blog/scaling-multimodal-foundation-models-in-torchmultimodal-with-pytorch-distributed/) here and trying to train flava with torchmm. However, training with ddp and activation checkpointing gives the following error. 

`
  File "/data/root/anaconda3/envs/torchdata/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/data/root/anaconda3/envs/torchdata/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 493 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
`
I also tried some other configurations as below, only ddp + checkpoint gives the above error. I'm wondering if there is some other change we need to make to the code. 

| launch | activation checkpoint | result |
------------ | -------------| -------------
ddp | &check; | &cross;
ddp | &cross; | &check;
fsdp | &check; | &check;

My Env: pytorch=1.13.1, cuda 11.7, torchmultimodal(via pip, from source) and I launched my script with
`torchrun --rdzv_endpoint="localhost:1234" --nproc_per_node=4 -m flava.native.train config=flava/native/configs/pretrain_debug.yaml`

Many thanks in advance!

**Comment by enmalik** [comment]
Hi @rxqy, thanks for bringing this to our attention. We're looking into active checkpointing with DDP.

In the meantime, please continue using FSDP (or no active checkpointing with DDP).
