### ISSUE TITLE
[DOCUMENTATION] Fix FLAVA example's link in the page Introducing Trochmultimodal

### ISSUE THREAD

**Issue by alcazar90** [facebookresearch/multimodal#407]
### 🚀 The feature, motivation and pitch

The FLAVA example's link in the page [_Introducing Torchmultimodal_](https://pytorch.org/blog/introducing-torchmultimodal/) is wrong, and it's pointing out to the paper.

Should be: https://github.com/facebookresearch/multimodal/tree/main/examples/flava
Instead: https://arxiv.org/abs/2112.04482

### Additional context

![Screenshot 2023-02-23 at 16 23 14](https://user-images.githubusercontent.com/14035919/221009618-e32414af-9c2a-4206-9215-3b9e9efd9dde.png)

**Comment by cjyabraham** [comment]
This is done. I [changed 3 instances of this link on the page](https://github.com/pytorch/pytorch.github.io/pull/1302/files). LMK if that isn't what you want.

**Comment by ankitade** [comment]
Thanks @cjyabraham, I believe you changed 2 other references which are actually meant to be links to the paper. Only the one circled in the screenshot needs to be changes

**Comment by cjyabraham** [comment]
Sorry about that. It is now fixed: https://pytorch.org/blog/introducing-torchmultimodal/
