### ISSUE TITLE
Support for CoCa Model

### ISSUE THREAD

**Issue by mert-kurttutan** [facebookresearch/multimodal#414]
### 🚀 The feature, motivation and pitch

Is there any plan to add support for CoCa model?

The only platform where I could find a model with pretrained models is open_clip repo. I think it would be really valuable if you could add it in this library.

Note: https://github.com/mlfoundations/open_clip has some model with unofficial pretrained weights.

**Comment by pikapecan** [comment]
Hi, 
We don't have CoCa model support for now. Welcome developers to add new model types and contribute to multimodal lib!

**Comment by ankitade** [comment]
Hi @mert-kurttutan, thats a great idea and we have been looking into coca style models. Would you be interested in contributing this model to our library.

**Comment by ebsmothers** [comment]
Hi @mert-kurttutan, following up on this thread: we are planning to add CoCa support soon so please stay tuned.

**Comment by ebsmothers** [comment]
Closing this now that we have landed #506
