### ISSUE TITLE
OOM while finetuning flava

### ISSUE THREAD

**Issue by rishabhm12** [facebookresearch/multimodal#420]
### 🚀 The feature, motivation and pitch

Hi guys,
I am trying to finetune flava on my custom dataset. I am also using mixed-precision but still getting OOM. I am running this using ddp on a single node multi-gpu (Nvidia A10) where in each gpu has 24G memory. 
These are the configs:
**Config:**
`training:
  _target_: flava.definitions.TrainingArguments
  lightning:
    max_steps: 30000
    gpus: -1
    val_check_interval: 1.0
    num_sanity_val_steps: 0
    strategy: ddp
    precision: 16
  lightning_checkpoint:
    dirpath: "./test_ckpt/"
    filename: flava-{epoch:02d}-{step}
    save_last: true
    every_n_train_steps: null
    save_on_train_epoch_end: true
    verbose: true
  lightning_load_from_checkpoint: null
  seed: -1
  batch_size: 128
  num_workers: 10
  learning_rate: 2e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  warmup_steps: 2000`
  
  **Errror:**

`    attn = attn / torch.sqrt(torch.tensor(q.shape[-1]))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 3; 22.06 GiB total capacity; 20.40 GiB already allocated; 28.44 MiB free; 20.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epoch 0: : 0it [00:14, ?it/s]`

The paper mentions flava-full is trained using a batch_size of 8192. Can you tell me which gpu was used for training the flava-full model?
Also, if you guys can suggest any workarounds which could help me here other than reducing batch_size, it would be very helpful
Thank you!

**Comment by ankitade** [comment]
The paper most likely use v100 with 32G memory
