### ISSUE TITLE
Cannot fine-tune CLIP model in GPU

### ISSUE THREAD

**Issue by LioYao** [facebookresearch/multimodal#525]
### 🚀 The feature, motivation and pitch

Hello!
I'm now fine-tuning the clip_vit_b16 model from models.clip.model. I also use CLIPTransform and torchvision's CocoCaptions function to perform image and text preprocessing on the MSCOCO dataset. Moreover, the input data to the model is an image-text pair (one image corresponds to one of the five texts). But when I loaded the image, text and model into the GPU using .to(deivce), I found that the program reported an error, which is "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!". May I ask how to solve it?
clip.txt is my code, please check it.
[clip.txt](https://github.com/facebookresearch/multimodal/files/14477717/clip.txt)

### Alternatives

We printed out the device where the image, text and model parameters are located and found that they were all in cuda:0. Therefore, we were surprised why we reported an error that all tensors were not in the same device. We have already installed the relevant third-party libraries.

**Comment by ebsmothers** [comment]
Hi @LioYao thanks for creating the issue. I suspect that the issue is with `ContrastiveLossWithTemperature`. Note that this loss contains a [parameter](https://github.com/facebookresearch/multimodal/blob/dbeed9724bc9099be173c86871df7d41f3b7e58c/torchmultimodal/modules/losses/contrastive_loss_with_temperature.py#L183), which should also be moved to the GPU. Can you try calling `.to(device)` on your loss as well?

**Comment by LioYao** [comment]
Thanks for your answer @ebsmothers. 
When I moved the loss to GPU, the same error still appeared. I printed the devices about image, text, model's parameters and loss's parameters and found that they are all in cuda:0. Most importantly, the error still occurs in "image_embeddings, text_embeddings = model(image,text)". The final traceback point of the error is in the scaled_dot_product_attention function. I wonder whether the multi-head attention mechanism forcibly copies the GPU data to the CPU when processing data.

**Comment by ebsmothers** [comment]
Hi @LioYao, strangely I cannot reproduce this error on my end, your script runs fine for me. A couple requests that will help with debugging:

1) Can you share the version of torch and other dependencies you're using (e.g. if in a conda env just paste the output of `conda list`)? 
2) What hardware are you running on?
3) Can you paste the full stack trace you're seeing?

In the meantime, a couple other suggestions (not sure that they will work until I have more info). One is to explicitly run in a device context manager, i.e. you can wrap everything in a `with torch.cuda.device(0):` block. Then you shouldn't need to call `.to(device)` anymore either. A second suggestion is to toggle different kernels for `scaled_dot_product_attention`. E.g. you can do

```
with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_mem_efficient=False, enable_math=False):
  image_embeddings, text_embeddings = model(image, text)
```

to enable the flash attention kernel and disable the other kernels. This may not solve your problem, but I would be interested to see if the same error repros under all of the different kernels.

**Comment by kartikayk** [comment]
Hi @LioYao, I tried the following very simple setup and this works just fine for me. So I'm not able to reproduce your error. Do you mind trying this simple version and seeing what you get?

```
model= clip_vit_b16(pretrained=False)
model = model.to('cuda:0')
# define loss and other things needed for training
clip_loss = ContrastiveLossWithTemperature()
optimizer = torch.optim.AdamW(model.parameters(),0.0225)

text = torch.randint(0, 49408, (1, 77), dtype=torch.long).to('cuda:0')
image = torch.randn(1, 3, 224, 224).to('cuda:0')

image_embeddings, text_embeddings = model(image, text)
loss = clip_loss(image_embeddings, text_embeddings)
loss.backward()
optimizer.step()
optimizer.zero_grad()

print(optimizer.param_groups[0]['params'][0].device)
print(image_embeddings.device)
print(text_embeddings.device)
```
And the output is:

```
cuda:0
cuda:0
cuda:0
```

**Comment by LioYao** [comment]
Thanks for your answer @ebsmothers and @kartikayk. Based on your tips, I found out that it was my environment problem. When I used a new environment, I found that the code could be run on the GPU. The possible explanation is that I mixed conda and pip when configuring the environment, causing multiple different versions of libraries to exist at the same time. Thanks again for your help.
